### ISSUE TITLE
Feature Request: Showing text inside circle

### ISSUE THREAD

**Issue by luixal** [passsy/android-HoloCircularProgressBar#2]
It would be great to be able to show some text inside the circle (completed %, just a "loading" message, etc...).

I've done it putting a FrameLayout with a TextView above the HoloCircularProgressBar and it looks nice (see screenshots*) and works smoothly, but would be greater to have it natively on the widget itself :)

*Screenshots:
[Screenshot 1](http://s24.postimg.org/g9h5y051x/Screenshot_2013_05_11_17_12_56.png)
[Screenshot 2](http://s24.postimg.org/w6fxupxg5/Screenshot_2013_05_11_17_21_17.png)

**Comment by passsy** [comment]
I thought about this feature. I'm also using it with a TextView above the HoloCircularProgressBar. see [here](http://s11.postimg.org/gscdskbwz/2013_05_11_19_10_15.png).

But I didn't add this because it's so easy.

I oriented the HoloCircularProgressBar by the ProgressBar from the SDK and the standard one doesn't display a percentage or something either.
