### ISSUE TITLE
Error  : No resource found that matches the give name : attr ' '

### ISSUE THREAD

**Issue by donglp1810** [passsy/android-HoloCircularProgressBar#21]
when I try to add this library to android studio 
I have to archive folder like: 
![archive](https://cloud.githubusercontent.com/assets/7262510/2679123/876470ee-c16d-11e3-9b27-f2dfa7821152.PNG)
But I acquired bug like:
![bug](https://cloud.githubusercontent.com/assets/7262510/2679125/8fa5c5b4-c16d-11e3-9e03-04a287d75afe.PNG)
You can help me fix this bug and guide how add this library to android studio 

p/s : I following this guide 
http://stackoverflow.com/questions/20310164/how-to-import-eclipse-library-project-from-github-to-android-studio-project

**Comment by passsy** [comment]
had the same issues porting this lib to android studio. the solution is to clean the project. 
`./gradlew clean`

also make sure the lib is added to the main module in the `build.gradle` 

```
dependencies {
    ....
    compile project(':HoloCircularProgressBar')
}
```

I also found this bug report: https://code.google.com/p/android/issues/detail?id=57569

The fix is available since Android Studio 0.5.4

> I pushed 0.5.4 with this fix. It'll be available shortly.
