### ISSUE TITLE
When I change the stroke width, it also adds more padding.

### ISSUE THREAD

**Issue by gomera** [passsy/android-HoloCircularProgressBar#31]
If I have a box of 100x100, when using a stroke width of 1dp, the circule will fill the whole box. If I increase the stroke, the circule gets smaller and smaller adding a padding.

1dp
![circule stroke 1dp](https://cloud.githubusercontent.com/assets/1063134/4394915/1469b928-4426-11e4-9723-e5159110cbf0.png)

10dp
![circule stroke 10dp](https://cloud.githubusercontent.com/assets/1063134/4394918/1eaaa58c-4426-11e4-9a8a-466275058c5b.png)

20dp
![circule stroke 20dp](https://cloud.githubusercontent.com/assets/1063134/4394923/24dfadf8-4426-11e4-863e-8c4343861d49.png)

**Comment by passsy** [comment]
It's because of the `app:thumb_visible="false"` 

![screen shot 2014-09-26 at 16 02 20](https://cloud.githubusercontent.com/assets/1096485/4421648/c4bcde76-4585-11e4-9dd4-efba02463f5c.png)

I've forgot to exclude the thumb thickness if it's disabled in [`#onMeasure`](https://github.com/passsy/android-HoloCircularProgressBar/blob/development/library/src/de/passsy/holocircularprogressbar/HoloCircularProgressBar.java#L336)

fixed in development branch (5ded49efe83eda6cff144b9e3834e3b426935703)

![screen shot 2014-09-26 at 16 45 10](https://cloud.githubusercontent.com/assets/1096485/4422292/bab5a312-458b-11e4-98e1-99233cae6f95.png)
