### ISSUE TITLE
text in the center of progress bar

### ISSUE THREAD

**Issue by letz** [passsy/android-HoloCircularProgressBar#9]
Its possible to have text in the center of the progress bar?

**Comment by passsy** [comment]
See #2. It's very easy. place textview in the center and fill it with the value.

I don't implemented it, because it's not clear what you want to see as value. 0 - 100? 00:00:00 - 00:01:00? 0 - 1?
And I don't know your preferred font and text size. I don't want to mix all TextView XML attributes into the CircularProgressBar.
